
--We can have join scripts that are this long in SQL. In order not to create these scripts over and over again,
--we collect them in a view table to make them more understandable. 
--We can create it as "Create view (viewname) as (required script)".

CREATE VIEW VWFiRSTCREATE
AS
SELECT
U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE,
A. ADDRESSTEXT ACIKADRES,
O.ID SIPARISID, O.DATE_ SIPARISTARIHI, ITM. ITEMCODE URUNKODU, ITM. ITEMNAME URUNADI, ITM. BRAND MARKA,
OD. AMOUNT MIKTAR, OD. UNITPRICE BIRIMFIYAT, OD. LINETOTAL SATIRTOPLAMI
FROM
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U. ID=O. USERID
INNER JOIN ADDRESS A ON A. ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID


--Now we can directly query the view table. In the query, we specified the new name of the column with "as". 
--Now we can search by the name of this new column.
SELECT * FROM VWORDERS
WHERE SEHIR='İSTANBUL'|



--Here we create a script to get the report of sales by month. 
--Here we gave the name of the month directly, but it can be requested as a number or 
--it can be requested with its short names (ock, branch, etc.).
--For this reason, we created this view in order not to deal with each change one by one.
CREATE VIEW VW_aylaraGoreSatislar
AS
SELECT
DATEPART (YEAR, O.DATE_) YIL,
CASE
WHEN DATEPART (MONTH, O.DATE_)=1 THEN 'OCAK' --
WHEN DATEPART (MONTH, O.DATE_)=2 THEN 'ŞUBAT'
WHEN DATEPART (MONTH, O.DATE_)=3 THEN 'MART'
WHEN DATEPART (MONTH, O.DATE_)=4 THEN 'NİSAN'
WHEN DATEPART (MONTH, O.DATE_)=5 THEN 'MAYIS'
WHEN DATEPART (MONTH, O.DATE_)=6 THEN 'HAZİRAN'
WHEN DATEPART (MONTH, O.DATE_)=7 THEN 'TEMMUZ'
WHEN DATEPART (MONTH, O.DATE_)=8 THEN 'AĞUSTOS'
WHEN DATEPART (MONTH, O.DATE_)=9 THEN 'EYLÜL'
WHEN DATEPART (MONTH, O.DATE_)=16 THEN 'EKİM'
WHEN DATEPART (MONTH, O.DATE_)=11 THEN 'KASIM'
WHEN DATEPART (MONTH, O.DATE_)=12 THEN 'ARALIK'
END AS AY,
SUM (AMOUNT) TOPLAMMIKTAR, SUM (LINETOTAL) TOPLAMTUTAR, COUNT (OD. ID) URUNSAYISI,
COUNT (DISTINCT O.ID) AS MUSTERISAYISI
FROM
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD. ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A. TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O. ID
GROUP BY DATEPART (YEAR, O.DATE_), DATEPART (MONTH, O.DATE_)
ORDER BY DATEPART (YEAR, O.DATE_), DATEPART (MONTH, O.DATE_)
